name: sc2-msspe
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ivar=1.0.1
  - minimap2=2.17
  - samtools=1.9
  - bcftools=1.9
  - seqtk=1.3
  - trim-galore=0.6.5
  - multiqc=1.8
  - quast=5.0.2
  - numpy=1.18.1
  - pandas=1.0.3
  - seaborn=0.10.0
  - biopython=1.76 
  - pysam=0.15.3
